[development]
address = "localhost"
port = 8000
workers = 4
keep_alive = 5

[staging]
address = "0.0.0.0"
port = 8000
workers = 4
keep_alive = 5

[production]
address = "0.0.0.0"
port = 8000
workers = 4
keep_alive = 5